spring.application.name=SB-UserManagementProject

spring.datasource.url=jdbc:mysql://localhost:3306/csrdb
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=Sharath@1234

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.security.user.name=sharath
spring.security.user.password=abcd1234

server.port=8080